---
platform: linux


inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: director-state

params:
  STEMCELL_NAME: null

outputs:
  - name: bats-config

run:
  path: bosh-stemcells-ci/ci/tasks/bats/iaas/gcp/prepare-bats-config.sh
