#!/bin/bash

BOSH=/var/vcap/bosh
NTP_SERVER_FILE=$BOSH/etc/ntpserver
if [ ! -f $NTP_SERVER_FILE ]; then
  exit
fi

exec > $BOSH/log/sync-time.out
exec 2>&1

CHRONY_TIME_SOURCES_FILE=/etc/chrony/sources.d/bosh.sources

cat > $CHRONY_TIME_SOURCES_FILE <<EOF
# created by $0
EOF

for ip in $( cat $NTP_SERVER_FILE ); do
  echo "server $ip iburst" >> $CHRONY_TIME_SOURCES_FILE
done

chronyc reload sources
chronyc waitsync 10
