---
platform: linux


inputs:
- name: bosh-blobstore-cli
- name: bosh-linux-stemcell-builder
- name: bosh-stemcells-ci

outputs:
- name: bosh-linux-stemcell-builder
  path: bosh-linux-stemcell-builder-out

run:
  path: bosh-stemcells-ci/ci/tasks/bump-bosh-blobstore-cli.sh
