platform: linux


inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: usn-log-in
  - name: usn-gh-json

run:
  path: bosh-stemcells-ci/ci/tasks/check-usn-packages.sh

params:
  OS:
  ESM_TOKEN:
