---
name: stemcell-acceptance-tests

releases:
- name: syslog
  version: latest

stemcells:
- alias: default
  os: ((os_name))
  version: ((stemcell_version))

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: default
  stemcell: default
  vm_type: default
  instances: 1
  networks:
  - {name: default}
  azs: [z1]
  jobs:
  - name: syslog_forwarder
    release: syslog
    properties:
      syslog:
        address: 127.0.0.1
        port: 5123
        transport: udp
