---
platform: linux


inputs:
- name: builder-src
- name: bosh-stemcells-ci
- name: us-light-stemcell
- name: cn-north-light-stemcell
  optional: true
- name: us-gov-light-stemcell
  optional: true

outputs:
- name: light-stemcell

run:
  path: bosh-stemcells-ci/ci/tasks/light-aws/merge-builds
