#!/bin/bash

set -e

if [ "" == "${1:-}" ] ; then
  echo "ERROR: include an image name as the first argument" 2>&1
  exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
IMAGE_NAME="$1"
DOCKER_IMAGE=${DOCKER_IMAGE:-bosh/$IMAGE_NAME}

# $UID is a readonly variable set by bash by default.
NEW_UID="$UID"
NEW_GID="$(id -g)"

if [[ "$UID" == 0 ]]; then
  echo "This script is not intended to be run as root..."
  echo "Passing UID to container as 1000..."
  NEW_UID=1000
fi

if [[ "$NEW_GID" == 0 ]]; then
  echo "This script is not intended to be run as root..."
  echo "Passing GID to container as 1000..."
  NEW_GID=1000
fi

if [[ "$IMAGE_NAME" == "os-image-stemcell-builder" || \
      "$IMAGE_NAME" == "os-image-stemcell-builder-bionic" ]] ; then
  USER_OPTION="--user=$NEW_UID:$NEW_GID"
elif [[ "$IMAGE_NAME" == "suse-os-image-stemcell-builder" ]] ; then
  USER_OPTION="-e LOCAL_USER_ID=$(id -u "$USER")"
fi

pushd "$IMAGE_NAME"
  docker build                      \
    --build-arg USER_ID="$NEW_UID"  \
    --build-arg GROUP_ID="$NEW_GID" \
    -t "$DOCKER_IMAGE"              \
    .
popd

exec docker run --privileged -v "$DIR/../..:/opt/bosh" --workdir /opt/bosh "$USER_OPTION" -t -i "$DOCKER_IMAGE"
