---
platform: linux


inputs:
  - name: bosh-deployment
  - name: bosh-stemcells-ci
  - name: bosh-linux-stemcell-builder

outputs:
  - name: director-state

params:
  PIPELINE_LABEL: # required - GCP label (pipeline=<value>) for the resources this task creates


run:
  path: bosh-stemcells-ci/ci/tasks/gcp/deploy-director-ipv6.sh
