#!/bin/bash
# THESE SCRIPTS ARE EXECUTED IN LEXICAL ORDER. MAKE SURE TO CHECK IF ANYTHING ELSE (CURRENTLY MONIT) WRITES OTHER CGROUP BASED RULES TO AVOID INTERFERENCE. IT'S PROBABLY AGOOD IDEA TO -A DROPS AND -I ACCEPTS

source /var/vcap/bosh/etc/nats-access-helper.sh


# Give the agent access to Monit right away
if iptables -t mangle -C POSTROUTING -d 127.0.0.1 -p tcp --dport 2822 \
            -m cgroup --cgroup "${nats_isolation_classid}" -j ACCEPT
then
  /bin/true
else
    iptables -t mangle -I POSTROUTING -d 127.0.0.1 -p tcp --dport 2822 \
             -m cgroup --cgroup "${nats_isolation_classid}" -j ACCEPT
fi

until [[ -f /var/vcap/bosh/settings.json ]]; do sleep 10; done
NATS_URL=$(cat /var/vcap/bosh/settings.json | sed 's#.*\("mbus"\):"\(.*\)",.*#\2#g' )

# CHECK IF THIS IS A CREATE ENV. 
if grep '^https' <<< ${NATS_URL}; then 
  echo "create-env, skipping iptables for nats"
else

  BOSH_IP_PORT=$( cut -f2 -d@ <<< ${NATS_URL} )
  BOSH_IP=$( cut -f1 -d: <<< ${BOSH_IP_PORT} )
  BOSH_PORT=$( cut -f2 -d: <<< ${BOSH_IP_PORT} )

  if [[ "${BOSH_IP_PORT}" != "" ]]; then
  cat << EOF
    if iptables -t mangle -C POSTROUTING -d ${BOSH_IP} -p tcp --dport ${BOSH_PORT} \
          -m cgroup --cgroup "${nats_isolation_classid}" -j ACCEPT
    then
      /bin/true
    else
        iptables -t mangle -I POSTROUTING -d ${BOSH_IP} -p tcp --dport ${BOSH_PORT} \
           -m cgroup --cgroup "${nats_isolation_classid}" -j ACCEPT
    fi
    if iptables -t mangle -C POSTROUTING -d ${BOSH_IP} -p tcp --dport ${BOSH_PORT} \
          -m cgroup \! --cgroup "${nats_isolation_classid}" -j DROP
    then
      /bin/true
    else
        iptables -t mangle -A POSTROUTING -d ${BOSH_IP} -p tcp --dport ${BOSH_PORT} \
           -m cgroup \! --cgroup "${nats_isolation_classid}" -j DROP
    fi
  EOF
  else
    echo "no nats protocoll connection found. assuming create-env"
  fi

fi


