---
jobs:
  - name: start-job
    serial: true
    plan:
      - get: bosh-linux-stemcell-builder

  - name: build-ubuntu-trusty
    plan:
      - get: bosh-linux-stemcell-builder
        trigger: true
        passed:
          - start-job
      - task: build
        file: bosh-linux-stemcell-builder/ci/os-images/tasks/build.yml
        privileged: true
        params:
          OPERATING_SYSTEM_NAME:      ubuntu
          OPERATING_SYSTEM_VERSION:   trusty
      - put: ubuntu-trusty-tarball
        params:
          file: os-image/ubuntu-trusty.tgz
          acl: public-read

resources:
  - name: bosh-linux-stemcell-builder
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-linux-stemcell-builder.git
      branch: {{branch}}

  #
  # ubuntu-trusty
  #

  - name: ubuntu-trusty-tarball
    type: s3
    source:
      bucket: {{osimage_bucket}}
      versioned_file: bosh-ubuntu-trusty-os-image.tgz
      access_key_id: {{osimage_aws_access_key}}
      secret_access_key: {{osimage_aws_secret_key}}
