name: SBOM scan

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */1 * * *'

jobs:
  SBOM-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: sbom

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: sbom
        scan-ref: sbom.spdx.json
        format: sarif
        output: trivy-results.sarif

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
